version: '3.3'

services:
  express:
    build: 
      context: ./api
      dockerfile: ../Dockerfile.express 
    image: local/express
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/          # mounts empty folder so npm can install on the image
    restart: always
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true      # enable fs event forwarding for file change detection (webpack)