version: '3.3'

services:
   mongo:
    image: mongo
    restart: "no"
    #volumes:
    #  - ./data/mongo:/data/db      # Mac/Linux: uncomment to persist data
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root