version: '3.3'

services:
   mysql:
    image: mysql:5.7
    restart: "no"
    #volumes:
    #  - ./data/mysql:/var/lib/mysql    # Mac/Linux: uncomment to persist data
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=react
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root